### ISSUE TITLE
When running main.py encountered an error while testing its own dataset

### ISSUE THREAD

**Issue by Drangonliao123** [Tengfei-Wang/external-internal-inpainting#7]
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()            
  File "main.py", line 27, in main
    train(opt.pyramid_height, mask, img, img_gray,  torch.cuda.FloatTensor, opt)
  File "main.py", line 77, in train
    mask_var_pyr, img_var_pyr, img_gray_var_pyr  = get_pyramids(mask, img, img_gray, pyramid_height, dtype)
  File "main.py", line 67, in get_pyramids
    img_gray_var_pyr.append(get_pyramid_image(img_gray, w_n, h_n)[:,:1,:,:].type(dtype))
  File "main.py", line 33, in get_pyramid_image
    img = np.array(img).transpose(2,0,1)/ 255.  
ValueError: axes don't match array

I spent a long time trying to solve the problem, but I still failed. I hope I can get your help. Thank you and look forward to your reply！

**Comment by shuzizihemu** [comment]
PIL读取图像的问题。你得把main函数中的一些代码进行修改
`    img = Image.open(opt.img_path).convert('RGB')
    img_gray = Image.open(opt.gray_path).convert('RGB')
    mask = Image.open(opt.mask_path).convert("L")`
就可以了

**Comment by shuzizihemu** [comment]
> 

PIL读取图像的问题。你得把main函数中的一些代码进行修改
img = Image.open(opt.img_path).convert('RGB')
 img_gray = Image.open(opt.gray_path).convert('RGB') 
mask = Image.open(opt.mask_path).convert("L")
就可以了
